### PR TITLE
fix: Use initialState prop instead of useParams in installation-page and remove Matomo

### PR DESCRIPTION
**Pull request by Ldoppea**
The installation page is composed of multiple steps (presentation,
security, hint, configureExtension)

When accessing the page, we want to be able to specify in the URL the
step that should be displayed

This is used in a specific scenario where we redirect to
cozy-settings's change password page. When the password is changed,
then cozy-settings should redirect to the step that was displayed
before

In previous implementation, we used `useParams` from `react-router`
(legacy from old cozy-password only website). But as we are displaying
this component from an Angular website, then the routing is not handled
from React anymore

Instead of trying to make `useParams` work, we chose to inject an
`initialStep` prop from the Angular context. Then the URL param reading
would be done from the Angular context.

Also since react-router is not used anymore, then the InstallationPage
step is not synchronized anymore with the URL. So instead of using a
path (i.e. `installation/hint`), we chose to convert this param to a
QueryParams (i.e. `installation?initialStep=hint`), this would prevent
any confusion

___

This PR also removes references to Matomo and cleaned some unused files

> **Warning**
> I tried to upgrade react-router to 6.3.0 but it requires a Typescript version that is incompatible with the current Angular version
> As react-router is only used in a few places (to display a `<Link>`) then I consider it would be too expansive compared to the benefits if we try to make the upgrade.
> Feel free to comment if you still think we should do the upgrade

### CODE REVIEW

**Review by zatteo — COMMENTED** [review]
Code looks good (but Angular beginner so...)

**Review by acezard — APPROVED** [review]
I think the comment for this commit: https://github.com/cozy/cozy-pass-web/pull/89/commits/8c818d74c9f1d1a4b6b9fd3a9da34eeaa054b771 could be copied somewhere more visible, the info seems important enough. up to you

**Comment by Ldoppea** [comment]
> I think the comment for this commit: [8c818d7](https://github.com/cozy/cozy-pass-web/commit/8c818d74c9f1d1a4b6b9fd3a9da34eeaa054b771) could be copied somewhere more visible, the info seems important enough. up to you

You mean somewhere in the code?

**Comment by acezard** [comment]
> > I think the comment for this commit: [8c818d7](https://github.com/cozy/cozy-pass-web/commit/8c818d74c9f1d1a4b6b9fd3a9da34eeaa054b771) could be copied somewhere more visible, the info seems important enough. up to you
> 
> You mean somewhere in the code?

Not sure where, maybe a md file in the repo yes. This is just a suggestion

**Comment by Ldoppea** [comment]
I'm not sure where to put this and I'm not sure that this would help much (this code is not so important as no-one noticed the bug in the last year) so I'll merge this as is, but we can still discuss about this.

**Pull request merged**
